### ISSUE TITLE
mastercard icon is missing

### ISSUE THREAD

**Issue by leaguecodeuk** [hiqdev/payment-icons#1]
Thank you very much for the icon pack. 
I couldn't find **master card** icon.
Can please add master card icon.

**Comment by hiqsol** [comment]
You are right.
We just use maestro icon instead.

**Comment by SilverFire** [comment]
Added: https://github.com/hiqdev/payment-icons/commit/aad778b0c12d6d0558dd0c4d82230f75e3c006d8
