### ISSUE TITLE
Add new icon ADVcash, LTC and other?

### ISSUE THREAD

**Issue by Volodya1234** [hiqdev/payment-icons#2]
Hi.

Please add ADVcash, Litecoin icon.

**Comment by hiqsol** [comment]
Could you please provide these icons?
It would be best if you made pull request.

**Comment by Volodya1234** [comment]
https://advcash.com/i/social.png
http://i.imgur.com/XjqSZE4.png - full text

**Comment by Volodya1234** [comment]
Many currencies are now used to pay for hosting. Advcash one with them.
I use the icons for the list of payment options. And you have found a practically large list with beautiful icons.

**Comment by SilverFire** [comment]
Will add

**Comment by SilverFire** [comment]
Done https://github.com/hiqdev/payment-icons/releases/tag/0.1.4
