### ISSUE TITLE
Add BCH, DASH, XMR, ETH, ZEC

### ISSUE THREAD

**Issue by Volodya1234** [hiqdev/payment-icons#4]
Hi!

This is currency too at the moment.

https://www.bitcoincash.org/
https://www.dash.org/ / https://www.dash.org/promotional-graphics/
https://getmonero.org/ / http://static.getmonero.org/images/opengraph/logo.png
https://www.ethereum.org/ / http://bitcoinist.com/wp-content/themes/bitcoinist/img/ETHEREUM-LOGO-2.png
https://z.cash/ru/ / https://z.cash/theme/images/zcash-logo-gold.png

Even Webmoney was added as Bitcoin Cash.

**Comment by SilverFire** [comment]
Thank you, we will add the icons

**Comment by SilverFire** [comment]
Done: https://github.com/hiqdev/payment-icons/releases/tag/0.1.5
