### ISSUE TITLE
Add icons for systems provided by Omnipay library

### ISSUE THREAD

**Issue by hiqsol** [hiqdev/payment-icons#5]
See the list here:

https://github.com/thephpleague/omnipay#payment-gateways

Braintree, Skrill, Stripe in the first place.

**Comment by hiqsol** [comment]
2CheckOut
Authorize.net
PayU
ASSIST
LiqPay
Paysera
UnionPay

**Comment by tafid** [comment]
Workpiece
[PaymentIcons.tar.gz](https://github.com/hiqdev/payment-icons/files/1421627/PaymentIcons.tar.gz)

**Comment by SilverFire** [comment]
Done: https://github.com/hiqdev/payment-icons/releases/tag/0.1.5
