### ISSUE TITLE
Нет иконки МИРа

### ISSUE THREAD

**Issue by ivan-cc** [hiqdev/payment-icons#6]
В наборе отсутствует иконка платежной системы [Мир](https://mironline.ru/).

**Comment by hiqsol** [comment]
Pull request ?

**Comment by ivan-cc** [comment]
К сожалению не владею гитом. Но нашел сам логотип:
http://evgenykatyshev.ru/projects/mir-logo/mir-logo.svg

**Comment by hiqsol** [comment]
Ok. А фотошопом владеете? Можете сделать png'шки как здесь? 
https://github.com/hiqdev/payment-icons/tree/master/src/assets/png

Я найду заготовки для фотошопа.

**Comment by ivan-cc** [comment]
Сделал png'шки.
[png.zip](https://github.com/hiqdev/payment-icons/files/2694918/png.zip)

**Comment by hiqsol** [comment]
Отлично! Большое спасибо!
Добавил.
