### ISSUE TITLE
New logo of VISA

### ISSUE THREAD

**Issue by ivan-cc** [hiqdev/payment-icons#7]
You are using an old logo.

Here is the new logo (png - lg,md,xs,sm):

[visa.zip](https://github.com/hiqdev/payment-icons/files/2694951/visa.zip)

**Comment by hiqsol** [comment]
Добавлю в ближайшее время.

**Comment by SilverFire** [comment]
Сделано в коммите 790c1c065570ee9bdaf3cf32cff3f8033181039b

**Comment by hiqsol** [comment]
Thank you for icons!
